language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - 6
  - 4
before_script:
  - npm prune && npm cache clean --force
  - npm install
script:
  - npm run test:prod
after_success:
  - npm run semantic-release
